"""add extraction job input fields

Revision ID: 023f4afcf020
Revises: 0edcc17dc323
Create Date: 2026-09-25 22:24:25.663704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '023f4afcf020'
down_revision: Union[str, Sequence[str], None] = '0edcc17dc323'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extraction_runs', sa.Column('url', sa.Text(), nullable=False))
    op.add_column('extraction_runs', sa.Column('duration_minutes', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('extraction_runs', 'duration_minutes')
    op.drop_column('extraction_runs', 'url')
    # ### end Alembic commands ###
