"""add lead location website and google_maps_url

Revision ID: e3591be2d84b
Revises: 023f4afcf020
Create Date: 2026-09-25 22:38:40.747541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3591be2d84b'
down_revision: Union[str, Sequence[str], None] = '023f4afcf020'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('location', sa.Text(), nullable=True))
    op.add_column('leads', sa.Column('website', sa.Text(), nullable=True))
    op.add_column('leads', sa.Column('google_maps_url', sa.String(length=1000), nullable=True))
    op.create_index(op.f('ix_leads_google_maps_url'), 'leads', ['google_maps_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_google_maps_url'), table_name='leads')
    op.drop_column('leads', 'google_maps_url')
    op.drop_column('leads', 'website')
    op.drop_column('leads', 'location')
    # ### end Alembic commands ###
